import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { ArrowLeft, CheckCircle2, KeyRound, LogOut, Mail, Pencil, Save, ShieldCheck, User, X } from "lucide-react";
import { authFetch, type AuthUser } from "../auth";

type ProfileProps = { user: AuthUser; businessName: string; onUserUpdated: (user: AuthUser) => void; onSignOut: () => void; onBack: () => void };

function Profile({ user, businessName, onUserUpdated, onSignOut, onBack }: ProfileProps) {
  const [editing, setEditing] = useState(false); const [name,setName]=useState(user.name); const [email,setEmail]=useState(user.email); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  const [passwordOpen,setPasswordOpen]=useState(false); const [currentPassword,setCurrentPassword]=useState(""); const [newPassword,setNewPassword]=useState(""); const [confirmPassword,setConfirmPassword]=useState("");
  useEffect(()=>{setName(user.name);setEmail(user.email)},[user]);
  const saveProfile=async(e:FormEvent)=>{e.preventDefault();setError("");setMessage("");if(!name.trim()||!email.trim())return setError("Name and email are required.");setSaving(true);try{const r=await authFetch("/api/auth/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name.trim(),email:email.trim()})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"Unable to update profile.");onUserUpdated(d.user);setEditing(false);setMessage("Profile updated successfully.");}catch(err){setError(err instanceof Error?err.message:"Unable to update profile.");}finally{setSaving(false);}};
  const changePassword=async(e:FormEvent)=>{e.preventDefault();setError("");setMessage("");if(newPassword.length<8)return setError("New password must be at least 8 characters.");if(newPassword!==confirmPassword)return setError("New passwords do not match.");setSaving(true);try{const r=await authFetch("/api/auth/change-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({current_password:currentPassword,new_password:newPassword})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"Unable to change password.");setCurrentPassword("");setNewPassword("");setConfirmPassword("");setPasswordOpen(false);setMessage("Password changed successfully.");}catch(err){setError(err instanceof Error?err.message:"Unable to change password.");}finally{setSaving(false);}};
  return <div className="mx-auto max-w-5xl space-y-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-violet-400">Account Management</p><h3 className="mt-1 text-3xl font-bold">User Profile</h3><p className="mt-1 text-slate-400">Manage your account details, security and session.</p></div><button onClick={onBack} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2.5 text-sm text-slate-300 hover:bg-white/[0.08]"><ArrowLeft size={16}/> Back</button></div>
  {(message||error)&&<div className={`rounded-xl border px-4 py-3 text-sm ${error?"border-red-400/20 bg-red-400/5 text-red-300":"border-emerald-400/20 bg-emerald-400/5 text-emerald-300"}`}>{error||message}</div>}
  <div className="grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><section className="rounded-2xl border border-white/10 bg-white/[0.035] p-6 shadow-2xl shadow-black/20 backdrop-blur-xl"><div className="flex flex-wrap items-center gap-5"><div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-blue-500 text-2xl font-bold">{user.name.charAt(0).toUpperCase()}</div><div><p className="text-2xl font-bold">{user.name}</p><p className="mt-1 text-sm text-slate-400">{user.role}</p><div className="mt-3 inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/5 px-3 py-1.5 text-xs text-emerald-300"><CheckCircle2 size={14}/> Account active</div></div></div><div className="my-6 border-t border-white/10"/>
  {!editing?<><div className="flex items-center justify-between"><div><h4 className="text-lg font-semibold">Personal Details</h4><p className="mt-1 text-sm text-slate-500">Your account information.</p></div><button onClick={()=>setEditing(true)} className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs text-slate-300 hover:bg-white/[0.06]"><Pencil size={14}/> Edit Profile</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><ProfileField icon={<User size={17}/>} label="Name" value={user.name}/><ProfileField icon={<Mail size={17}/>} label="Email" value={user.email}/><ProfileField icon={<ShieldCheck size={17}/>} label="Role" value={user.role}/><ProfileField icon={<KeyRound size={17}/>} label="Password" value="••••••••"/></div></>:<form onSubmit={saveProfile} className="space-y-4"><div className="flex items-center justify-between"><h4 className="text-lg font-semibold">Edit Profile</h4><button type="button" onClick={()=>setEditing(false)} className="text-slate-500 hover:text-white"><X size={18}/></button></div><Input label="Name" value={name} onChange={setName}/><Input label="Email" type="email" value={email} onChange={setEmail}/><button disabled={saving} className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-blue-600 px-4 py-3 text-sm font-semibold disabled:opacity-60"><Save size={16}/>{saving?"Saving...":"Save Changes"}</button></form>}
  </section><section className="rounded-2xl border border-white/10 bg-white/[0.035] p-6 shadow-2xl shadow-black/20 backdrop-blur-xl"><div className="rounded-xl border border-violet-500/15 bg-violet-500/5 p-4"><p className="text-xs uppercase tracking-wider text-violet-300">Workspace</p><p className="mt-2 text-lg font-semibold">{businessName}</p><p className="mt-1 text-sm text-slate-400">Inventory Management System</p></div><div className="mt-5"><h4 className="text-lg font-semibold">Security & Session</h4><p className="mt-1 text-sm text-slate-500">Manage your password and current session.</p></div><div className="mt-5 space-y-3"><button onClick={()=>setPasswordOpen(v=>!v)} className="flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm font-semibold text-slate-300 hover:bg-white/[0.06]"><KeyRound size={17}/>{passwordOpen?"Close Password Form":"Change Password"}</button>{passwordOpen&&<form onSubmit={changePassword} className="space-y-3 rounded-xl border border-white/10 bg-white/[0.025] p-4"><Input label="Current Password" type="password" value={currentPassword} onChange={setCurrentPassword}/><Input label="New Password" type="password" value={newPassword} onChange={setNewPassword}/><Input label="Confirm New Password" type="password" value={confirmPassword} onChange={setConfirmPassword}/><button disabled={saving} className="w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold disabled:opacity-60">{saving?"Updating...":"Update Password"}</button></form>}<button onClick={onSignOut} className="flex w-full items-center justify-center gap-2 rounded-xl border border-red-400/20 bg-red-400/5 px-4 py-3 text-sm font-semibold text-red-300 hover:bg-red-400/10"><LogOut size={17}/> Sign Out</button></div></section></div></div>;
}
function Input({label,type="text",value,onChange}:{label:string;type?:string;value:string;onChange:(v:string)=>void}){return <div><label className="mb-2 block text-sm text-slate-300">{label}</label><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-sm outline-none focus:border-violet-500/50"/></div>}
function ProfileField({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="rounded-xl border border-white/10 bg-white/[0.025] p-4"><div className="flex items-center gap-2 text-slate-500">{icon}<span className="text-xs">{label}</span></div><p className="mt-2 truncate text-sm font-medium text-slate-200">{value}</p></div>}
export default Profile;
