import { useState, type FormEvent, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, Eye, EyeOff, LockKeyhole, Mail, Package, UserRound } from "lucide-react";
import { API_BASE_URL, setToken } from "../auth";
import { AuthShell } from "./Login";

type RegisterProps = { onSuccess: () => void; onSignIn: () => void };
function Register({ onSuccess, onSignIn }: RegisterProps) {
  const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const submit=async(e:FormEvent)=>{e.preventDefault();setError("");if(!name.trim()||!email.trim()||!password)return setError("Fill in all required fields.");if(password.length<8)return setError("Password must be at least 8 characters.");if(password!==confirm)return setError("Passwords do not match.");setLoading(true);try{const r=await fetch(`${API_BASE_URL}/api/auth/register`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name.trim(),email:email.trim(),password})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"Unable to create account.");setToken(d.access_token,true);onSuccess();}catch(err){setError(err instanceof Error?err.message:"Unable to create account.");}finally{setLoading(false);}};
  return <AuthShell><button onClick={onSignIn} className="mb-5 flex items-center gap-2 text-sm text-slate-500 hover:text-white"><ArrowLeft size={16}/> Back to sign in</button><div className="mb-7 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-blue-500 shadow-xl shadow-violet-500/20"><Package size={27}/></div><h1 className="mt-5 text-3xl font-bold">Create account</h1><p className="mt-2 text-sm text-slate-400">Set up your Inventory Pro workspace</p></div><form onSubmit={submit} className="space-y-4"><Field icon={<UserRound size={17}/>} label="Full Name" value={name} onChange={setName} placeholder="Kunal Kumar"/><Field icon={<Mail size={17}/>} label="Email" type="email" value={email} onChange={setEmail} placeholder="you@example.com"/><div><label className="mb-2 block text-sm text-slate-300">Password</label><div className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 focus-within:border-violet-500/50"><LockKeyhole size={17} className="text-slate-500"/><input value={password} onChange={e=>setPassword(e.target.value)} type={show?"text":"password"} placeholder="At least 8 characters" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-600"/><button type="button" onClick={()=>setShow(v=>!v)} className="text-slate-500 hover:text-white">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></div><Field icon={<LockKeyhole size={17}/>} label="Confirm Password" type={show?"text":"password"} value={confirm} onChange={setConfirm} placeholder="Re-enter your password"/>{error&&<div className="rounded-xl border border-red-400/20 bg-red-400/5 px-4 py-3 text-sm text-red-300">{error}</div>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-blue-600 px-4 py-3.5 text-sm font-semibold shadow-lg shadow-violet-600/20 disabled:opacity-60">{loading?"Creating account...":<>Create Account <ArrowRight size={17}/></>}</button></form><p className="mt-7 text-center text-sm text-slate-500">Already have an account? <button onClick={onSignIn} className="font-medium text-violet-400">Sign in</button></p></AuthShell>;
}
function Field({icon,label,type="text",value,onChange,placeholder}:{icon:ReactNode;label:string;type?:string;value:string;onChange:(v:string)=>void;placeholder:string}){return <div><label className="mb-2 block text-sm text-slate-300">{label}</label><div className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 focus-within:border-violet-500/50"><span className="text-slate-500">{icon}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-600"/></div></div>}
export default Register;
